import type { NextPage } from "next";
import Head from "next/head";

import { useGetAllAbandonedCartsQuery } from "../generated/graphql";

const Configuration: NextPage = () => {
  const [{ data, error, fetching }] = useGetAllAbandonedCartsQuery();

  if (fetching) {
    return <div>Fetching data...</div>;
  }
  if (error) {
    return <div>Error fetching data:{error.message}</div>;
  }

  return (
    <div>
      <Head>
        <title>Abandoned Carts App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Abandoned Checkouts</h1>
        <ol>
          {data?.checkouts?.edges.map((checkout) => (
            <>
              <li key={checkout.node.id}>
                <p>Id: {checkout.node.id}</p>
                <div>Created: {checkout.node.created}</div>
              </li>
            </>
          ))}
        </ol>
      </main>
    </div>
  );
};

export default Configuration;
